### ISSUE TITLE
Plugin fails with sbt `1.4.0`

### ISSUE THREAD

**Issue by cipriandrei10** [Duhemm/sbt-errors-summary#47]
The plugin fails with sbt version `1.4.0`, plugin version `0.6.3`
```
[info] welcome to sbt 1.4.0 (Private Build Java 1.8.0_265)
[info] loading settings for project global-plugins from idea.sbt ...
[info] loading global plugins from ~/.sbt/1.0/plugins
[info] loading settings for project some-project from plugins.sbt ...
[info] loading project definition from ~/some-project/project
[info] loading settings for project some-project from build.sbt ...
[info] set current project to some-project
[info] compiling 1 Scala source to ~/some-project/target/classes ...
[error] scala.MatchError: sbt.errorssummary.Reporter@15f3f9cf (of class sbt.errorssummary.Reporter)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2146)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2099)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:40)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error]         at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2096)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compileIncremental) scala.MatchError: sbt.errorssummary.Reporter@15f3f9cf (of class sbt.errorssummary.Reporter)
```

**Comment by ritschwumm** [comment]
see https://github.com/sbt/sbt/issues/5935

**Comment by cipriandrei10** [comment]
It looks like the plugin works now with the new version of sbt `1.4.1`. Will close this. Thanks!
